TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#=============================
# Build a support module called <APPNAME>


# timer.dbd will be created and installed
DBD += timer.dbd
timer_DBD += base.dbd
timer_DBD += geminiRecords.dbd


#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

